#!/bin/bash

git submodule init
git submodule update

cd ${BASH_SOURCE[0]%/*}
. .scripts-common
check_create_cd "../fuerte-build"
cmake -DCMAKE_BUILD_TYPE=Debug \
      -DFUERTE_TESTS=TRUE \
    ../fuerte && make -j $(nproc)
