#!/bin/bash
. .scripts-common
check_create_cd ".build-dev"

#CMAKE_ARGS="-DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl"

#cmake -DCMAKE_BUILD_TYPE=Debug -DFUERTE_TESTS=ON -DFUERTE_EXAMPLES=ON .. && make -j $(nproc) && \
cmake $CMAKE_ARGS -DCMAKE_BUILD_TYPE=Debug -DFUERTE_TESTS=ON .. && 
    make -j $(nproc) && \
    ctest --output-on-failure --verbose

