#!/bin/bash

conf="$1"
source_dir="$2"

shift 2

(

cd $source_dir || { echo "failed to cd into source"; exit 1; }

case $conf in
    default)
        ./build/bin/arangod \
            --server.authentication false \
            --server.endpoint vst+tcp://127.0.0.1:8530 \
            --server.endpoint http+tcp://127.0.0.1:8529 \
            --log.level communication=trace \
            --log.level requests=trace \
            ../arangodb-data/

    ;;

    debug)
        ./build/bin/arangod \
            --server.authentication false \
            --server.endpoint vst+tcp://127.0.0.1:8530 \
            --server.endpoint http+tcp://127.0.0.1:8529 \
            --log.level communication=debug \
            --log.level requests=debug \
            ../arangodb-data/

    ;;

    default-gdb)
        gdb --args ./build/bin/arangod \
            --server.authentication false \
            --server.endpoint vst+tcp://127.0.0.1:8530 \
            --server.endpoint http+tcp://127.0.0.1:8529 \
            --log.level communication=trace \
            --log.level requests=trace \
            ../arangodb-data/
    ;;

    nospam)
        ./build/bin/arangod \
            --server.authentication false \
            --server.endpoint vst+tcp://127.0.0.1:8530 \
            --server.endpoint http+tcp://127.0.0.1:8529 \
            ../arangodb-data/
    ;;

    vstonly)
        ./build/bin/arangod \
            --server.authentication false \
            --server.endpoint vst+tcp://127.0.0.1:8529 \
            ../arangodb-data/
    ;;

    *)
        echo "no valid configuration (default, nospam, vstonly)"
    ;;

esac
)
