// Do not edit, file generated by CMake

#ifndef FUERTE_FUERTE_VERSION_H
#define FUERTE_FUERTE_VERSION_H

#define VERSION_STRING "0.1.0"
#define VERSION_MAJOR 0
#define VERSION_MINOR 1
#define VERSION_PATCH 0

#endif  // FUERTE_FUERTE_VERSION_H
